name: test
on:
- pull_request
env: 
  MAILGUN_API_KEY: test
  SITE_API_URL: test
  SITE_FRONTEND_URL: test
  NO_REPLY_EMAIL: test
  POSTGRES_HOSTNAME: postgres
  MAP_PATH: map_parsing/map.json
jobs:
  bionic:
    container: 
      image: vapor/swift:5.2-bionic
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: vapor
          POSTGRES_DB: metroquiz_testing
          POSTGRES_PASSWORD: password
    steps:
    - uses: actions/checkout@v1
    - name: Setup python3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install python depency
      run: python3 -m pip install bs4 cssutils tinycss2 soupsieve webencodings
    - name: Generate map for testing
      working-directory: ./map_parsing
      run: python3 parse_html.py
    - run: swift test --enable-test-discovery --sanitize=thread
